# Generated by Django 5.2 on 2025-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_media_file_alter_media_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
