# Generated by Django 5.2 on 2025-04-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_media_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='media',
            name='uploaded_by',
        ),
    ]
