# Generated by Django 5.2 on 2025-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('editor', 'Editor'), ('user', 'User')], default='admin', max_length=20),
        ),
    ]
