# Generated by Django 5.2 on 2025-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_media_title_mediabatch_media_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
